### ISSUE TITLE
The OpenVPN server has no status file

### ISSUE THREAD

**Issue by No1zzz** [cyberorg/openvpn-web-gui#1]
$config['openvpn']['status']     = '/var/log/openvpn/openvpn-status.log';
ls /var/log/openvpn/openvpn-status.log
/var/log/openvpn/openvpn-status.log
Where should be status file?

**Comment by cyberorg** [comment]
Check your openvpn config 
grep status /etc/openvpn/*

**Comment by No1zzz** [comment]
grep status /etc/openvpn/*
/etc/openvpn/server.conf:status /var/log/openvpn/openvpn-status.log

**Comment by No1zzz** [comment]
Is it not supporting?

**Comment by cyberorg** [comment]
I am not sure of your issue. If you do not have /var/log/openvpn/openvpn-status.log then you have to check your openvpn configuration /et/openvpn/server.conf, it should have these 2 lines.

status /var/log/openvpn/openvpn-status.log
status-version 2

If you still do not get the log file,  you'd have to check with openvpn/your distro forum, IRC etc.

**Comment by No1zzz** [comment]
I have this file,but does not have status-version 2 
With this line work fine!
TY.
