### ISSUE TITLE
Guide regrarding webbased openvpn gui

### ISSUE THREAD

**Issue by ctrlaltvikas** [cyberorg/openvpn-web-gui#3]
Hi Jigish,

I saw this repo of yours and would like to take some advice and guidance in this regard. I have been trying to create a web enabled(cross-broswer) solution for openvpn such that eveything can be done via browser with no need to go to command line. Could you help me or provide me some source concerning this?

Thanks

**Comment by cyberorg** [comment]
Try webmin
